# -*- coding: utf-8 -*-
"""Pneumonia classifier

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12cJWZ-U7mbH8CZ1k-YEXE5zBer770E7F
"""

!pip install -q kaggle

from google.colab import files

files.upload()

! mkdir ~/.kaggle

! cp kaggle.json ~/.kaggle/

! chmod 600 ~/.kaggle/kaggle.json

! kaggle datasets download -d paultimothymooney/chest-xray-pneumonia

!unzip -q chest-xray-pneumonia.zip -d /content/chest_xray

import os
import cv2
import numpy as np
from sklearn.model_selection import train_test_split

data_dir = '/content/chest_xray/chest_xray'
train_path = os.path.join(data_dir, 'train')
test_path = os.path.join(data_dir, 'test')
val_path = os.path.join(data_dir, 'val')

images = []
labels = []
for label in ['NORMAL', 'PNEUMONIA']:
    class_path = os.path.join(train_path, label)
    for img_name in os.listdir(class_path):
        img_path = os.path.join(class_path, img_name)
        images.append(img_path)
        labels.append(0 if label == 'NORMAL' else 1) # 0 for Normal, 1 for Pneumonia

from tensorflow.keras.applications import ResNet50
from tensorflow.keras.layers import Dense, Flatten, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam

# ResNet50 typically expects 3-channel input (RGB).
# Since X-rays are grayscale (1 channel), you'll need to expand the grayscale channel
# to 3 channels by repeating it. The input_shape should reflect this.
# Target size for ResNet50 is usually (224, 224) or (256, 256) for best performance,
# but it can be adjusted. Let's assume 224x224.
IMAGE_SIZE = (256, 256)
INPUT_SHAPE = (IMAGE_SIZE[0], IMAGE_SIZE[1], 3) # 3 channels for ResNet input

# Load ResNet50 pre-trained on ImageNet
# include_top=False means we don't include the original classification head of ResNet50
# weights='imagenet' uses weights trained on the ImageNet dataset
base_model = ResNet50(weights='imagenet', include_top=False, input_shape=INPUT_SHAPE)

# Freeze the layers of the base model
# This prevents the pre-trained weights from being updated during the initial training phase,
# preserving the general features learned from ImageNet.
for layer in base_model.layers:
    layer.trainable = False

# Add custom classification head on top of ResNet50
x = base_model.output
x = Flatten()(x) # Flatten the output of the convolutional base
x = Dense(256, activation='relu')(x) # A dense layer
x = Dropout(0.5)(x) # Dropout for regularization
predictions = Dense(1, activation='sigmoid')(x) # Output layer for binary classification (Pneumonia/Normal)

model = Model(inputs=base_model.input, outputs=predictions)

model.compile(
    optimizer=Adam(learning_rate=0.0001),
    loss='binary_crossentropy',
    metrics=['accuracy', 'precision', 'recall']
)

print("Model compiled successfully!")
print(f"Total parameters: {model.count_params():,}")

# Print model summary
model.summary()

#PREPROCESSING AND AUGMENTATION

from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Data augmentation for training only
train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    horizontal_flip=True,
    zoom_range=0.2,
    fill_mode='nearest'
)

# Only rescaling for validation and test (no augmentation)
val_test_datagen = ImageDataGenerator(rescale=1./255)

# Use your existing paths and IMAGE_SIZE
train_generator = train_datagen.flow_from_directory(
    train_path,  # '/content/chest_xray/chest_xray/train'
    target_size=IMAGE_SIZE,  # (256, 256)
    batch_size=32,
    class_mode='binary'
)

validation_generator = val_test_datagen.flow_from_directory(
    val_path,    # '/content/chest_xray/chest_xray/val'
    target_size=IMAGE_SIZE,  # (256, 256)
    batch_size=32,
    class_mode='binary'
)

test_generator = val_test_datagen.flow_from_directory(
    test_path,   # '/content/chest_xray/chest_xray/test'
    target_size=IMAGE_SIZE,  # (256, 256)
    batch_size=32,
    class_mode='binary',
    shuffle=False  # Important for consistent evaluation
)

from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint

# Define callbacks
callbacks = [
    EarlyStopping(
        monitor='val_loss',
        patience=5,
        restore_best_weights=True,
        verbose=1
    ),
    ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.2,
        patience=3,
        min_lr=1e-7,
        verbose=1
    ),
    ModelCheckpoint(
        'best_pneumonia_model.h5',
        monitor='val_accuracy',
        save_best_only=True,
        verbose=1
    )
]

import tensorflow as tf
print("GPU:", tf.test.gpu_device_name())
!nvidia-smi

from tensorflow.keras.layers import GlobalAveragePooling2D, Dense, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
import tensorflow as tf # Import tensorflow with the alias tf

# Add custom classification layers on top of ResNet50
x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(512, activation='relu')(x)
x = Dropout(0.5)(x)
predictions = Dense(1, activation='sigmoid')(x)  # Binary classification

# Create the complete model
model = Model(inputs=base_model.input, outputs=predictions)

# Compile the model for Phase 1 (frozen base model)
model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy', 'precision', 'recall']
)

print("Model compiled successfully!")
print(f"Total parameters: {model.count_params():,}")
print(f"Trainable parameters: {sum([tf.keras.backend.count_params(w) for w in model.trainable_weights]):,}")


# PHASE 1: TRANSFER LEARNING

print("\n" + "="*50)
print("STARTING PHASE 1: TRANSFER LEARNING")
print("="*50)
print("Base model layers are frozen - only training classifier layers")

epochs_phase1 = 10
print(f"Training for {epochs_phase1} epochs...")

history_phase1 = model.fit(
    train_generator,
    epochs=epochs_phase1,
    validation_data=validation_generator,
    callbacks=callbacks,
    verbose=1
)

print("✅ Phase 1 training completed!")

print("\n" + "="*50)
print("STARTING PHASE 2: FINE-TUNING")
print("="*50)

# Unfreeze the top layers of ResNet50
print("Unfreezing last 20 layers of ResNet50...")
base_model.trainable = True  # First make base model trainable

# Then freeze early layers, only unfreeze last 20
for layer in base_model.layers[:-20]:
    layer.trainable = False

print(f"Trainable parameters after unfreezing: {sum([tf.keras.backend.count_params(w) for w in model.trainable_weights]):,}")

# Recompile with lower learning rate for fine-tuning
model.compile(
    optimizer=Adam(learning_rate=0.00001),  # Much lower learning rate
    loss='binary_crossentropy',
    metrics=['accuracy', 'precision', 'recall']
)

print("Model recompiled with lower learning rate (1e-5)")

# Continue training
epochs_phase2 = 10
print(f"Fine-tuning for {epochs_phase2} epochs...")

history_phase2 = model.fit(
    train_generator,
    epochs=epochs_phase1 + epochs_phase2,  # Total epochs: 20
    validation_data=validation_generator,
    callbacks=callbacks,
    verbose=1,
    initial_epoch=epochs_phase1  # Start from epoch 10, go to epoch 20
)


print("✅ Fine-tuning completed!")

print("\n" + "="*50)
print("TRAINING COMPLETED!")
print("="*50)

# Combine training histories
total_epochs = epochs_phase1 + epochs_phase2

# Get the actual metric names from history
metric_keys = list(history_phase1.history.keys())
print(f"Actual metric keys: {metric_keys}")


print("Phase 1 history keys:", list(history_phase1.history.keys()))
print("Phase 2 history keys:", list(history_phase2.history.keys()))
print("Phase 1 history length:", len(history_phase1.history))
print("Phase 2 history length:", len(history_phase2.history))

# Create combined history with actual key names
combined_history = {}
for key in metric_keys:
    if key in history_phase1.history and key in history_phase2.history:
        combined_history[key] = history_phase1.history[key] + history_phase2.history[key]
    else:
        print(f"Warning: Key '{key}' not found in both histories")

# Get final metrics using actual key names
# Since we can see the actual keys from your output, use them directly
if 'accuracy' in combined_history and 'val_accuracy' in combined_history:
    final_train_acc = combined_history['accuracy'][-1]
    final_val_acc = combined_history['val_accuracy'][-1]
    final_train_loss = combined_history['loss'][-1]
    final_val_loss = combined_history['val_loss'][-1]

    print(f"📊 FINAL TRAINING METRICS:")
    print(f"   Training Accuracy: {final_train_acc*100:.2f}%")
    print(f"   Validation Accuracy: {final_val_acc*100:.2f}%")
    print(f"   Training Loss: {final_train_loss:.4f}")
    print(f"   Validation Loss: {final_val_loss:.4f}")
else:
    print("⚠️ Could not find accuracy metrics in combined history")
    print(f"Available keys in combined_history: {list(combined_history.keys())}")

#GRAD-CAM IMPLEMENTATION

import tensorflow as tf
from tensorflow.keras.models import Model
# Import specific layer types for robust type checking
from tensorflow.keras.layers import Conv2D, Conv2DTranspose # Include Conv2DTranspose if your model might use it
import numpy as np
import cv2
import matplotlib.pyplot as plt
import tensorflow.keras.layers as layers # Import layers here


class GradCAM:
    """Grad-CAM implementation for CNN visualization"""

    def __init__(self, model, layer_name=None):
        self.model = model

        if not self.model.built:
            # Create a dummy input tensor with the expected input shape of the model
            # Assumes model.input_shape is available (e.g., (None, H, W, C))
            if self.model.input_shape:
                dummy_input_shape = (1,) + self.model.input_shape[1:]
                _ = self.model(tf.zeros(dummy_input_shape))
            else:
                raise ValueError("Model input shape could not be determined. Ensure model is built (e.g., by calling model.predict() once) or provide input_shape to model construction.")

        # Call find_target_layer as a method of the instance
        self.layer_name = layer_name or self._find_target_layer() # Renamed to _find_target_layer to indicate it's internal
        if self.layer_name is None:
            raise ValueError("No suitable target layer found for Grad-CAM. Please ensure your model has a convolutional layer before the final dense layers, or specify 'layer_name' manually.")


    # Move this function inside the class and make it a method
    def _find_target_layer(self): # Renamed to _find_target_layer and added self
        """Finds the name of the last convolutional layer in the model."""
        for layer in reversed(self.model.layers):
            # Check for Conv2D layers specifically
            if isinstance(layer, layers.Conv2D):
                return layer.name
        # If no Conv2D layer is found after checking all layers in reverse
        return None # Indicate that no suitable layer was found


    def generate_heatmap(self, img_array, class_index=None):
        """Generate Grad-CAM heatmap for a given image array."""

        # Create a model that maps the input image to the activations
        # of the last conv layer as well as the output predictions
        grad_model = Model(
            inputs=[self.model.inputs],
            outputs=[self.model.get_layer(self.layer_name).output, self.model.output]
        )

        # Compute the gradient of the top predicted class for our input image
        # with respect to the activations of the last conv layer
        with tf.GradientTape() as tape:
            conv_outputs, predictions = grad_model(img_array)

            if predictions.shape[-1] == 1: # Binary classification with single sigmoid output
                # For binary classification with a single sigmoid output neuron:
                # If class_index is None, we target the predicted class's probability neuron.
                # If class_index is 0 (Normal), we target 1 - prediction[0,0] (the probability of Normal).
                # If class_index is 1 (Pneumonia), we target prediction[0,0] (the probability of Pneumonia).
                if class_index is None: # Use the predicted class
                    target_class_prob = predictions[:, 0]
                elif class_index == 1: # Explicitly target Pneumonia
                    target_class_prob = predictions[:, 0]
                elif class_index == 0: # Explicitly target Normal
                    target_class_prob = 1 - predictions[:, 0]
                else:
                    raise ValueError("For binary classification, class_index must be 0, 1, or None.")
                class_channel = target_class_prob
            else: # Multi-class classification (softmax output)
                if class_index is None:
                    class_index = tf.argmax(predictions[0])
                class_channel = predictions[:, class_index]

        # Gradient of the output neuron (top predicted or chosen)
        # with regard to the output feature map of the last conv layer
        grads = tape.gradient(class_channel, conv_outputs)

        # Mean intensity of the gradient over a specific feature map channel
        pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))

        # Multiply each channel in the feature map array
        # by "how important this channel is" with regard to the top predicted class
        conv_outputs = conv_outputs[0] # Get rid of batch dimension
        # The '@' operator (matrix multiplication) works here because:
        # conv_outputs is (H, W, C)
        # pooled_grads[..., tf.newaxis] makes pooled_grads (C, 1)
        # Result is (H, W, 1), which is then squeezed.
        heatmap = conv_outputs @ pooled_grads[..., tf.newaxis]
        heatmap = tf.squeeze(heatmap) # Remove the last dimension (1)

        # Normalize the heatmap (ReLU operation to keep only positive gradients)
        heatmap = tf.maximum(heatmap, 0) # Apply ReLU
        max_heatmap_val = tf.math.reduce_max(heatmap)
        # Handle potential division by zero if heatmap is all zeros
        heatmap = tf.where(tf.math.equal(max_heatmap_val, 0), tf.zeros_like(heatmap), heatmap / max_heatmap_val)

        return heatmap.numpy()

    def visualize_heatmap(self, img_path, class_index=None, alpha=0.4, save_path=None):
        """Visualize Grad-CAM heatmap on image"""

        # Load and preprocess image
        # Ensure target_size matches your model's input expected (height, width)
        # If your model takes 3 channels (like ResNet50), but image is grayscale, handle conversion.
        # If IMAGE_SIZE is (W, H, C), img.size is (W, H)
        # Use the global IMAGE_SIZE which should be (256, 256)
        img = tf.keras.preprocessing.image.load_img(img_path, target_size=IMAGE_SIZE[:2])
        img_array = tf.keras.preprocessing.image.img_to_array(img)

        # If the model expects 3 channels but the image is grayscale (1 channel after img_to_array)
        if img_array.shape[-1] == 1 and self.model.input_shape[-1] == 3:
            img_array = np.concatenate([img_array, img_array, img_array], axis=-1)

        # Normalize pixel values to 0-1 range as expected by the model
        img_array_for_model = np.expand_dims(img_array, axis=0) / 255.0

        # Generate prediction
        prediction = self.model.predict(img_array_for_model, verbose=0)

        # Determine predicted class and confidence for display
        if prediction.shape[-1] == 1: # Binary classification
            predicted_class = int(prediction[0][0] > 0.5)
            confidence = prediction[0][0] if predicted_class == 1 else (1 - prediction[0][0])
            # If class_index is not specified for Grad-CAM, use the predicted class
            if class_index is None:
                class_index_for_heatmap = predicted_class
            else:
                class_index_for_heatmap = class_index
        else: # Multi-class classification
            predicted_class = tf.argmax(prediction[0]).numpy()
            confidence = prediction[0][predicted_class]
            if class_index is None:
                class_index_for_heatmap = predicted_class
            else:
                class_index_for_heatmap = class_index

        # Generate heatmap
        heatmap = self.generate_heatmap(img_array_for_model, class_index=class_index_for_heatmap)

        # Resize heatmap to match original image size (width, height)
        # img.size gives (width, height) for PIL images
        heatmap_resized = cv2.resize(heatmap, (img.size[0], img.size[1]))
        # Convert heatmap to a color map (JET is a common choice)
        heatmap_colored = cv2.applyColorMap(np.uint8(255 * heatmap_resized), cv2.COLORMAP_JET)

        # Convert original image to a NumPy array for visualization with OpenCV
        # Ensure it's in BGR format for cv2.addWeighted, and 3 channels
        img_array_vis = np.array(img)
        if img_array_vis.ndim == 2: # Grayscale image
             img_array_vis = cv2.cvtColor(img_array_vis, cv2.COLOR_GRAY2BGR)
        elif img_array_vis.shape[-1] == 1: # Grayscale with 1 channel dim
             img_array_vis = cv2.cvtColor(img_array_vis, cv2.COLOR_GRAY2BGR)
        else: # RGB image
            img_array_vis = cv2.cvtColor(img_array_vis, cv2.COLOR_RGB2BGR) # Convert to BGR for OpenCV


        # Create overlay using cv2.addWeighted for proper blending and type handling
        overlay = cv2.addWeighted(heatmap_colored, alpha, img_array_vis, 1 - alpha, 0)


        # Visualization using Matplotlib
        fig, axes = plt.subplots(1, 4, figsize=(20, 5))

        # Original image (Matplotlib expects RGB, so convert back from BGR if necessary)
        axes[0].imshow(cv2.cvtColor(img_array_vis, cv2.COLOR_BGR2RGB))
        axes[0].set_title('Original Image')
        axes[0].axis('off')

        # Heatmap
        axes[1].imshow(heatmap_resized, cmap='jet')
        axes[1].set_title('Grad-CAM Heatmap')
        axes[1].axis('off')

        # Overlay (Matplotlib expects RGB, so convert back from BGR)
        axes[2].imshow(cv2.cvtColor(overlay, cv2.COLOR_BGR2RGB))
        axes[2].set_title('Grad-CAM Overlay')
        axes[2].axis('off')

        # Prediction info
        class_names = ['Normal', 'Pneumonia'] # Assuming binary classification for pneumonia
        axes[3].text(0.1, 0.7, f'Prediction: {class_names[predicted_class]}',
                             fontsize=14, transform=axes[3].transAxes)
        axes[3].text(0.1, 0.5, f'Confidence: {confidence:.3f}',
                             fontsize=14, transform=axes[3].transAxes)
        axes[3].text(0.1, 0.3, f'Target Layer: {self.layer_name}',
                             fontsize=12, transform=axes[3].transAxes)
        axes[3].axis('off')

        plt.tight_layout()

        if save_path:
            plt.savefig(save_path, dpi=150, bbox_inches='tight')

        plt.show()

        return {
            'prediction': predicted_class,
            'confidence': confidence,
            'heatmap': heatmap_resized,
            'overlay': overlay
        }

    # The compute_heatmap and superimpose methods were not defined in the provided GradCAM class.
    # These seem to be intended as user-facing methods based on the final code cell.
    # However, the logic for generating the heatmap and the overlay is already present
    # in the `generate_heatmap` and `visualize_heatmap` methods.
    # `visualize_heatmap` already performs the superimposition and plotting.
    # It's likely that the last code cell is trying to use methods that don't exist
    # or are named differently. The `visualize_heatmap` method is the one that handles
    # generating the heatmap and displaying the overlay.

    # If you still want separate methods, they would need to be implemented.
    # For example:
    # def compute_heatmap(self, img_array_for_model, class_index=None):
    #     return self.generate_heatmap(img_array_for_model, class_index)
    #
    # def superimpose(self, original_img_array, heatmap, alpha=0.4):
    #     # This logic would need to be implemented based on the original_img_array
    #     # and the generated heatmap. This is already done inside visualize_heatmap.
    #     pass


# The standalone find_target_layer function definition outside the class should be removed.
# import tensorflow.keras.layers as layers # This import is now inside the class scope

# def find_target_layer(self): # This function definition is outside the class and should be removed
#     for layer in reversed(self.model.layers):
#         if isinstance(layer, layers.Conv2D):
#             return layer.name
#     # raise ValueError("No convolutional layer found") # This raise is also redundant
#     return None

import numpy as np
import cv2
import matplotlib.pyplot as plt
# Make sure you have the GradCAM class defined and imported if it's in a separate file

def analyze_sample_images(generator, gradcam_analyzer, model, num_samples=2):
    """Analyze sample images with Grad-CAM and display them.

    Args:
        generator: A Keras ImageDataGenerator flow_from_directory generator
                   (e.g., test_generator) providing batches of images.
        gradcam_analyzer: An instance of the GradCAM class.
        model: The trained Keras model used for predictions.
        num_samples: The number of sample images to display.
    """

    generator.reset() # Reset generator to ensure consistent samples from the start

    all_images_normalized = []
    all_true_labels = []

    # Collect enough samples to meet num_samples, batch by batch
    samples_collected = 0
    batch_count = 0
    while samples_collected < num_samples:
        try:
            # Get the next batch
            batch_x, batch_y = next(generator)
            batch_count += 1

            print(f"--- Collecting Batch {batch_count} ---")
            print(f"Images in current batch: {len(batch_x)}")

            if len(batch_x) == 0:
                print("WARNING: Empty batch received from generator. Breaking loop.")
                break

            all_images_normalized.extend(batch_x)
            all_true_labels.extend(batch_y)

            samples_collected += len(batch_x)
            print(f"Total samples collected so far: {samples_collected}")

        except StopIteration:
            print("Generator exhausted before collecting all desired samples.")
            break
        except Exception as e:
            print(f"Error getting batch from generator: {e}")
            break

    print(f"\nFinished collecting batches. Total images in 'all_images_normalized': {len(all_images_normalized)}")

    # If no samples were collected, return
    if not all_images_normalized:
        print("No samples collected from the generator. Cannot perform analysis.")
        return

    # Use only the first 'num_samples' images if more were collected than needed
    images_to_analyze = all_images_normalized[:num_samples]
    labels_to_analyze = all_true_labels[:num_samples]

    # Adjust num_samples if we collected fewer than requested
    actual_num_samples = len(images_to_analyze)
    if actual_num_samples == 0:
        print("No images available to analyze.")
        return

    print(f"Actual number of samples to plot: {actual_num_samples}")

    fig, axes = plt.subplots(2, actual_num_samples, figsize=(actual_num_samples * 4, 8))

    # Ensure axes is always a 2D array, even for a single image
    if actual_num_samples == 1:
        axes = np.array([axes]).reshape(2, 1)

    class_names = ['Normal', 'Pneumonia'] # Define your class names

    for i in range(actual_num_samples):
        img_normalized = images_to_analyze[i] # Image array, normalized (0-1)
        true_label = int(labels_to_labels[i]) # Corrected line: Use all_true_labels

        # 1. Prepare image for display and OpenCV operations:
        img_display = (img_normalized * 255).astype(np.uint8)

        if img_display.ndim == 2:
             img_display = cv2.cvtColor(img_display, cv2.COLOR_GRAY2BGR)
        elif img_display.shape[2] == 1:
             img_display = cv2.cvtColor(img_display, cv2.COLOR_GRAY2BGR)
        else:
            img_display = cv2.cvtColor(img_display, cv2.COLOR_RGB2BGR)

        # 2. Make prediction using the model (model expects normalized input)
        prediction = model.predict(np.expand_dims(img_normalized, axis=0), verbose=0)

        # Determine predicted class and confidence for binary classification
        predicted_class = int(prediction[0][0] > 0.5)
        confidence = prediction[0][0] if predicted_class == 1 else (1 - prediction[0][0])

        # 3. Generate heatmap using the GradCAM analyzer
        heatmap = gradcam_analyzer.generate_heatmap(np.expand_dims(img_normalized, axis=0))

        # 4. Process heatmap and create overlay:
        heatmap_resized = cv2.resize(heatmap, (img_display.shape[1], img_display.shape[0]))
        heatmap_colored = cv2.applyColorMap(np.uint8(255 * heatmap_resized), cv2.COLORMAP_JET)
        overlay = cv2.addWeighted(heatmap_colored, 0.4, img_display, 0.6, 0)

        # 5. Visualization using Matplotlib
        axes[0, i].imshow(cv2.cvtColor(img_display, cv2.COLOR_BGR2RGB))
        axes[0, i].set_title(f'True: {class_names[true_label]}\n'
                             f'Pred: {class_names[predicted_class]} (Conf: {confidence:.3f})')
        axes[0, i].axis('off')

        axes[1, i].imshow(cv2.cvtColor(overlay, cv2.COLOR_BGR2RGB))
        axes[1, i].set_title('Grad-CAM Overlay')
        axes[1, i].axis('off')

    plt.tight_layout()
    plt.show()

import os # This line is necessary!

def analyze_single_image(image_path, gradcam_analyzer):
    """Analyze a single image with detailed Grad-CAM visualization"""

    try:
        # Assuming gradcam_analyzer.visualize_heatmap correctly saves the image and returns prediction details
        result = gradcam_analyzer.visualize_heatmap(image_path, save_path=f'gradcam_analysis_{os.path.basename(image_path)}.png')

        print(f"\nAnalysis of {os.path.basename(image_path)}:")
        # Ensure 'prediction' and 'confidence' keys exist in the result dictionary
        if result and 'prediction' in result and 'confidence' in result:
            print(f"Prediction: {'Pneumonia' if result['prediction'] else 'Normal'}")
            print(f"Confidence: {result['confidence']:.3f}")
        else:
            print("Warning: Prediction results not found or incomplete in visualize_heatmap output.")

        return result

    except Exception as e:
        print(f"Error analyzing {image_path}: {str(e)}")
        return None

# Example usage - analyze specific images
print("\n" + "="*50)
print("GRAD-CAM ANALYSIS COMPLETE")
print("="*50)
print("\nTo analyze specific images, use:")
print("analyze_single_image('path/to/your/image.jpg', gradcam)")

# Run Grad-CAM visualization on a sample image
gradcam_analyzer = GradCAM(model)


import os
import random


if os.path.exists(test_path):
    pneumonia_samples = os.listdir(os.path.join(test_path, 'PNEUMONIA'))
    if pneumonia_samples:
        sample_img_name = random.choice(pneumonia_samples)
        sample_img_path = os.path.join(test_path, 'PNEUMONIA', sample_img_name)

        print(f"\nAnalyzing sample image: {sample_img_path}")
        gradcam_analyzer.visualize_heatmap(sample_img_path, class_index=1) # class_index=1 for Pneumonia

    normal_samples = os.listdir(os.path.join(test_path, 'NORMAL'))
    if normal_samples:
        sample_img_name = random.choice(normal_samples)
        sample_img_path = os.path.join(test_path, 'NORMAL', sample_img_name)

        print(f"\nAnalyzing sample image: {sample_img_path}")
        gradcam_analyzer.visualize_heatmap(sample_img_path, class_index=0) # class_index=0 for Normal
else:
    print(f"Test path not found at {test_path}. Cannot analyze sample images.")