# -*- coding: utf-8 -*-
"""U-net segmentation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aKxcvIjzPGtnvoB3gJ8Vbr8W275eGLnS
"""

!pip install -q kaggle

from google.colab import files

files.upload()

! mkdir ~/.kaggle

! cp kaggle.json ~/.kaggle/

! chmod 600 ~/.kaggle/kaggle.json

! kaggle datasets download -d paultimothymooney/chest-xray-pneumonia

!unzip -q chest-xray-pneumonia.zip -d /content/chest_xray

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
from torchvision import transforms
import os

data_dir = '/content/chest_xray/chest_xray'
train_path_raw = os.path.join(data_dir, 'train')
test_path_raw = os.path.join(data_dir, 'test')
val_path_raw = os.path.join(data_dir, 'val')

# Define paths for both NORMAL and PNEUMONIA images
train_normal_dir = os.path.join(train_path_raw, 'NORMAL')
train_pneumonia_dir = os.path.join(train_path_raw, 'PNEUMONIA')
val_normal_dir = os.path.join(val_path_raw, 'NORMAL')
val_pneumonia_dir = os.path.join(val_path_raw, 'PNEUMONIA')
test_normal_dir = os.path.join(test_path_raw, 'NORMAL')
test_pneumonia_dir = os.path.join(test_path_raw, 'PNEUMONIA')


# --- 2. Combine image paths (from image_32c296.png) ---
def get_all_images_from_directory(base_dir):
    images = []
    for root, _, files in os.walk(base_dir):
        for file in files:
            if file.lower().endswith(('.png', '.jpg', '.jpeg')):
                images.append(os.path.join(root, file))
    return images

train_normal_images = get_all_images_from_directory(train_normal_dir)
train_pneumonia_images = get_all_images_from_directory(train_pneumonia_dir)
val_normal_images = get_all_images_from_directory(val_normal_dir)
val_pneumonia_images = get_all_images_from_directory(val_pneumonia_dir)
test_normal_images = get_all_images_from_directory(test_normal_dir)
test_pneumonia_images = get_all_images_from_directory(test_pneumonia_dir)

train_images = train_normal_images + train_pneumonia_images
val_images = val_normal_images + val_pneumonia_images
test_images = test_normal_images + test_pneumonia_images

print(f"Combined Training Images: {len(train_images)}")
print(f"Combined Validation Images: {len(val_images)}")
print(f"Combined Test Images: {len(test_images)}")


# --- 3. Create directories for synthetic masks (from image_32c296.png) ---
synthetic_mask_dir = '/content/synthetic_lung_masks'
os.makedirs(synthetic_mask_dir, exist_ok=True)

# --- 4. Create synthetic masks (from image_32c296.png, depends on image_32c29e.png) ---
print("\nCreating synthetic lung masks...")

def create_synthetic_lung_masks(image_paths, mask_dir, image_size=(256, 256)):
    """
    Creates synthetic lung masks using simple thresholding and morphological operations.
    Saves the masks to mask_dir.
    """
    os.makedirs(mask_dir, exist_ok=True)
    from skimage.filters import threshold_otsu
    from skimage import morphology

    for img_path in image_paths:
        filename = os.path.basename(img_path)
        mask_filepath = os.path.join(mask_dir, filename.replace('.jpeg', '.png').replace('.jpg', '.png')) # Ensure mask is png

        if os.path.exists(mask_filepath):
            continue # Skip if mask already exists

        # Read image
        img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
        if img is None:
            # print(f"Warning: Could not read image {img_path}")
            continue

        img_resized = cv2.resize(img, image_size)

        # Apply Gaussian Blur
        blurred = cv2.GaussianBlur(img_resized, (5, 5), 0)

        # Threshold
        thresh = threshold_otsu(blurred)
        binary = blurred > thresh

        # Remove small objects and fill holes
        binary = morphology.remove_small_objects(binary, min_size=1000) # Adjust min_size as needed
        binary = morphology.remove_small_holes(binary, area_threshold=1000) # Adjust area_threshold

        # Convert to 0-255 range
        mask = (binary * 255).astype(np.uint8)

        # Save mask
        cv2.imwrite(mask_filepath, mask)
    print(f"Created/Checked {len(image_paths)} synthetic masks in {mask_dir}")


create_synthetic_lung_masks(train_images, os.path.join(synthetic_mask_dir, 'train_masks'))
create_synthetic_lung_masks(val_images, os.path.join(synthetic_mask_dir, 'val_masks'))
create_synthetic_lung_masks(test_images, os.path.join(synthetic_mask_dir, 'test_masks'))

model = UNet(n_channels=1, n_classes=1) # 1 input channel (grayscale), 1 output channel (binary mask)
model.to(device)
print(f"Model has {sum(p.numel() for p in model.parameters())} parameters")

transform = transforms.Compose([
    transforms.Resize((256, 256)), # Resize images to expected input size for U-Net
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485], std=[0.229]) # Normalization for grayscale images
])
# Define a basic transform for masks
mask_transform = transforms.Compose([
    transforms.Resize((256, 256)),
    transforms.ToTensor()
])

class LungDataset(Dataset):
    def __init__(self, image_paths, mask_dir=None, transform=None, mask_transform=None):
        """
        Initializes the LungDataset.

        Args:
            image_paths (list): List of paths to the images.
            mask_dir (str, optional): Directory containing the corresponding masks. Defaults to None.
            transform (callable, optional): Optional transform to be applied to images. Defaults to None.
            mask_transform (callable, optional): Optional transform to be applied to masks. Defaults to None.
        """
        self.image_paths = image_paths
        self.mask_dir = mask_dir
        self.transform = transform
        self.mask_transform = mask_transform



    def __len__(self):
        # Return the number of samples in your dataset
        return len(self.image_paths)

    def __getitem__(self, idx):
        # Load image and mask
        img_path = self.image_paths[idx]
        image = Image.open(img_path).convert('L') # Open image and convert to grayscale

        mask = None
        if self.mask_dir:
            # Construct mask path based on image path and mask_dir
            filename = os.path.basename(img_path).replace('.jpeg', '.png').replace('.jpg', '.png')
            mask_path = os.path.join(self.mask_dir, filename)
            if os.path.exists(mask_path):
                mask = Image.open(mask_path).convert('L') # Open mask and convert to grayscale

        # Apply transforms
        if self.transform:
            image = self.transform(image)

        if self.mask_transform and mask is not None:
            mask = self.mask_transform(mask)

        # Return the image and mask (or just image if no mask_dir)
        if mask is not None:
            return image, mask
        else:
            return image

train_dataset = LungDataset(train_images,
                            mask_dir=os.path.join(synthetic_mask_dir, 'train_masks'),
                            transform=transform,
                            mask_transform=mask_transform)
val_dataset = LungDataset(val_images,
                          mask_dir=os.path.join(synthetic_mask_dir, 'val_masks'),
                          transform=transform,
                          mask_transform=mask_transform)
test_dataset = LungDataset(test_images,
                           mask_dir=os.path.join(synthetic_mask_dir, 'test_masks'),
                           transform=transform,
                           mask_transform=mask_transform)

print(f"Train Dataset Size: {len(train_dataset)}")
print(f"Validation Dataset Size: {len(val_dataset)}")
print(f"Test Dataset Size: {len(test_dataset)}")

batch_size = 8
num_workers = 2 # Number of CPU workers for data loading
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=num_workers)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, num_workers=num_workers)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=num_workers)

lr = 1e-4 # Learning rate
optimizer = optim.Adam(model.parameters(), lr=lr)
scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, 'min', patience=5)

def train_model(model, train_loader, val_loader, num_epochs, optimizer, scheduler, device):
    train_losses = []
    val_losses = []

    print("\nStarting training...")
    for epoch in range(num_epochs):
        # Training phase
        model.train()
        current_train_loss = 0.0
        for images, masks in train_loader:
            images = images.to(device)
            masks = masks.to(device) # Masks should be 0/1 float tensors

            optimizer.zero_grad()
            outputs = model(images)

            # Ensure outputs and masks have same dimensions (especially channel dim for n_classes=1)
            # For n_classes=1, outputs.shape[1] should be 1
            if outputs.shape[1] == 2: # This condition might be from a different model config
                loss = combined_loss(outputs[:, 1, :, :].unsqueeze(1), masks) # Take the second channel if it's 2 classes
            else: # Assuming n_classes=1, outputs.shape[1] should be 1
                loss = combined_loss(outputs, masks)

            loss.backward()
            optimizer.step()
            current_train_loss += loss.item()

        train_loss = current_train_loss / len(train_loader)
        train_losses.append(train_loss)

        # Validation phase
        model.eval()
        current_val_loss = 0.0
        with torch.no_grad():
            for images, masks in val_loader:
                images = images.to(device)
                masks = masks.to(device)

                outputs = model(images)
                if outputs.shape[1] == 2:
                    loss = combined_loss(outputs[:, 1, :, :].unsqueeze(1), masks)
                else:
                    loss = combined_loss(outputs, masks)
                current_val_loss += loss.item()

        val_loss = current_val_loss / len(val_loader)
        val_losses.append(val_loss)

        scheduler.step(val_loss) # Adjust learning rate based on validation loss

        if (epoch + 1) % 1 == 0: # Print every epoch
            print(f"Epoch {epoch + 1}/{num_epochs}, Train Loss: {train_loss:.4f}, Val Loss: {val_loss:.4f}")

    print("Training complete.")
    return train_losses, val_losses

def predict_and_visualize(model, image_path, device='cuda', threshold=0.5):
    """
    Predicts segmentation mask and visualizes results.
    """
    model.eval() # Set model to evaluation mode
    # Image transformation for prediction
    transform_predict = transforms.Compose([
        transforms.Resize((256, 256)), # Resize to model input size
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485], std=[0.229])
    ])

    # Load and preprocess image
    image = Image.open(image_path).convert('L') # Convert to grayscale
    original_size = image.size # Store original size for display

    image_tensor = transform_predict(image).unsqueeze(0).to(device) # Add batch dimension and move to device

    with torch.no_grad():
        output = model(image_tensor)
        pred_mask = torch.sigmoid(output).squeeze(0) # Apply sigmoid and remove batch dimension

        pred_mask = (pred_mask > threshold).float() # Binarize the mask based on threshold

    # Convert to numpy for visualization
    image_np = image_tensor.squeeze().cpu().numpy() # Remove batch and channel dims, move to CPU, convert to numpy
    pred_mask_np = pred_mask.squeeze().cpu().numpy() # Squeeze, move to CPU, convert to numpy

    # Plot results
    fig, axes = plt.subplots(1, 3, figsize=(15, 5))

    # Original Image
    axes[0].imshow(image_np, cmap='gray')
    axes[0].set_title('Original Image')
    axes[0].axis('off')

    # Predicted Mask
    axes[1].imshow(pred_mask_np, cmap='gray')
    axes[1].set_title('Predicted Mask')
    axes[1].axis('off')

    # Overlay (optional: you might need to adjust alpha for better visibility)
    # Convert grayscale image to RGB to overlay mask
    image_rgb = cv2.cvtColor((image_np * 255).astype(np.uint8), cv2.COLOR_GRAY2RGB)
    overlay = image_rgb.copy()
    # Apply mask in red color
    overlay[pred_mask_np == 1] = [255, 0, 0] # Red color for segmented area

    alpha = 0.5 # Transparency of overlay
    final_overlay = cv2.addWeighted(image_rgb, 1 - alpha, overlay, alpha, 0)

    axes[2].imshow(final_overlay.astype(np.uint8))
    axes[2].set_title('Overlay')
    axes[2].axis('off')

    plt.tight_layout()
    plt.show() # Display the plot

    return pred_mask_np

if __name__ == '__main__':
    # Define epochs
    num_epochs = 10 # Start with a small number to test, then increase

    # Train the model
    train_losses, val_losses = train_model(model, train_loader, val_loader, num_epochs, optimizer, scheduler, device)

    # Plot training and validation losses (from image_32c279.png)
    plt.figure(figsize=(10, 5))
    plt.plot(range(num_epochs), train_losses, label='Train Loss')
    plt.plot(range(num_epochs), val_losses, label='Validation Loss')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.title('Training and Validation Loss')
    plt.legend()
    plt.grid(True)
    plt.show()

    # Save the trained model (from image_32c279.png)
    model_save_path = '/content/unet_lung_segmentation.pth'
    torch.save(model.state_dict(), model_save_path)
    print(f"\nModel saved to {model_save_path}")

    # --- Test a sample image and visualize (from image_32c279.png and image_32c2ba.png) ---
    if len(test_dataset) > 0:
        test_image_path = test_dataset.image_paths[0] # Get the first test image path
        print(f"\nPredicting and visualizing for sample test image: {test_image_path}")



        predicted_mask = predict_and_visualize(model, test_image_path, device=device)
    else:
        print("No test images available for prediction and visualization.")

